name: l2t_alpha
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.1.0
  flutter_bloc: ^7.1.0
  intl: ^0.17.0
  flow_builder: ^0.0.1
  formz: ^0.4.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_markdown: ^0.6.0
  url_launcher: ^6.0.3
  google_sign_in: ^5.0.1
  github_sign_in:
    git: https://github.com/Gene-Dana/dart-github-sign-in.git
  flutter_signin_button: ^2.0.0
  google_fonts: ^2.1.0

  authentication_repository:
    path: packages/authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  # bloc_test: ^8.0.0
  # mocktail: 0.0.1-dev.12
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/hoverLogo/
    - assets/logo/
  fonts:
    - family: Kreon
      fonts:
        - asset: fonts/Kreon-Bold.ttf
          weight: 700
        - asset: fonts/Kreon-Regular.ttf
